---
Faça você mesmo:
  
Tratar dados 'tempo.csv'
Aparência: sol, nublado, chuva 
Temperatura: -130 ~ 130 F
Umidade: 0 ~ 100
Jogar: sim/nao
Tratar valores NAs
---

```{r}

dados = read.csv("tempo.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(dados)
summary(dados)

```

Explorar dados (colunas categóricas):

```{r}

# Aparência:

summary(dados$Aparencia)
counts = table(dados$Aparencia)
counts
barplot(counts, main = "Aparência")

# Vento:

summary(dados$Vento)
counts = table(dados$Vento)
counts
barplot(counts, main = "Vento")

# Jogar:

summary(dados$Jogar)
counts = table(dados$Jogar)
counts
barplot(counts, main = "Jogar")

```

Explorar dados (colunas numéricas):

```{r}

# Temperatura:

summary(dados$Temperatura)
boxplot(dados$Temperatura, outline = F)
hist(dados$Temperatura)

# Umidade:

summary(dados$Umidade)
boxplot(dados$Umidade, outline = FALSE)
hist(dados$Umidade)

```

Valores faltantes - NAs:

```{r}

dados[!complete.cases(dados),]

```


```{r}

# Aparência:

unique(dados$Aparencia)
summary(dados$Aparencia)

# NAs

dados[is.na(dados$Aparencia),]

dados[dados$Aparencia == "menos",]$Aparencia = "sol"

# Remover levels não utilizados (levels são os valores que uma variável categórica pode assumir):

summary(dados$Aparencia)

dados$Aparencia = factor(dados$Aparencia)

summary(dados$Aparencia)

```
```{r}

# Vento:

unique(dados$Vento)
summary(dados$Vento)

# NAs:

dados[is.na(dados$Vento),]

dados[is.na(dados$Vento),]$Vento = "FALSO" # Escolhido por ser a moda desta coluna

# Remover levels não utilizados (levels são os valores que uma variável categórica pode assumir):

summary(dados$Vento)

# dados$Vento = factor(dados$Vento) - não necessário

# summary(dados$Vento) - não necessário

```



```{r}

# Temperatura:

summary(dados$Temperatura)

# Fora do domínio numérico:

dados[dados$Temperatura < -130 | dados$Temperatura > 130,]$Temperatura

# Se temos NAs:

dados[is.na(dados$Temperatura),]

# Substituir o valor fora do domínio por NA, para não interferir na mediana

median(dados$Temperatura, na.rm = TRUE)

dados$Temperatura <- ifelse(dados$Temperatura < -130 | dados$Temperatura > 130, NA, dados$Temperatura)

median(dados$Temperatura, na.rm = TRUE)

# Substituição:

dados[is.na(dados$Temperatura),]$Temperatura = median(dados$Temperatura, na.rm = TRUE)

# Buscamos novamente temperaturas anormais:

dados[dados$Temperatura < -130 | dados$Temperatura > 130,]

dados[is.na(dados$Temperatura),]

summary(dados$Temperatura)

```



```{r}

# Umidade:

summary(dados$Umidade)

# Fora do domínio numérico:

dados[dados$Umidade < 0 | dados$Umidade > 100,]$Umidade

# Se temos NAs:

dados[is.na(dados$Umidade),]

# Substituir os valores fora do domínio por NA:

dados$Umidade <- ifelse(dados$Umidade < 0 | dados$Umidade > 100, NA, dados$Umidade)

# Opção: preencher com mediana:

median(dados$Umidade, na.rm = TRUE)

# Substituição:

dados[is.na(dados$Umidade),]$Umidade = median(dados$Umidade, na.rm = TRUE)

# Buscamos novamente níveis de umidade anormais:

dados[dados$Umidade < 0 | dados$Umidade > 100,]

dados[is.na(dados$Umidade),]

summary(dados$Umidade)

```

